%% Set-up

%Make sure all EEGLAB functions are on the MATLAB path
[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab;
close all;

%Load GRP
load('StimulusAgent.GRP', '-mat');


%% Full design

GRP = FfdrGRP(GRP, ...
                'bg_factor_name', 'ExperimentType', ...
                'bins', 1:6, ...
                'wg_factor_names', {'Agent','StimulusMedium' }, ...
                'wg_factor_levels', [3, 2], ...
                'save_GRP', 'yes', ...
                'output_file', 'StimulusAgent.xlsx');

%% Within-group follow-ups

%Naive
load('StimulusAgent_naive.GND', '-mat');
GND_N = FclustGND(GND_N, ...
                'bins', 1:6, ...  
                'factor_names', {'Agent', 'StimulusMedium'}, ...  
                'factor_levels', [3, 2], ...
                'time_wind', time_wind, ...
                'chan_hood', chan_hood, ...
                'n_perm', n_perm, ...
                'save_GND', 'yes', ...
                'output_file', 'StimAgent_naive.xlsx');
            
%Prior
load('StimulusAgent_prior.GND', '-mat');
GND_P = FclustGND(GND_P, ...
                'bins', 1:6, ...  
                'factor_names', {'Agent', 'StimulusMedium'}, ...  
                'factor_levels', [3, 2], ...
                'save_GND', 'yes', ...
                'output_file', 'StimAgent_prior.xlsx');